# Generated by Django 4.2.2 on 2023-08-27 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=48, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('avatar', models.ImageField(default='profiles/avatar_default.png', upload_to='profiles/<django.db.models.fields.related.OneToOneField>')),
                ('game_account', models.CharField(blank=True, max_length=200, null=True)),
                ('team_status', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
