# Generated by Django 4.2.2 on 2023-10-07 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('link', models.CharField(max_length=200, unique=True, verbose_name='Ссылка')),
                ('preview_image', models.ImageField(blank=True, default='articles/post_default.svg', upload_to='articles/')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('link', models.CharField(max_length=200, unique=True, verbose_name='Ссылка')),
                ('image', models.ImageField(default='projects/project_default.svg', upload_to='projects/', verbose_name='Изображение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/articles/<django.db.models.fields.related.ForeignKey>')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.article')),
            ],
        ),
    ]
